version: '3.8'

services:
  nginx:
    build: .
    container_name: landing-page
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    # volumes:
    #   - ./ssl:/etc/nginx/ssl:ro

